# This script will kill the iperf process on each of the servers
# acting as an iperf server, which will result in all iperf
# processes being stopped.
#
---

- hosts: servers
  remote_user: ansible
  tasks:
    - name: Kills iperf processes
      shell: pkill iperf3

